"""Generate the IEEE and thesis companion repositories from the flagship.

WHY THIS EXISTS
---------------
`16.537 m/s` appears in nine places in the flagship. Four hand-maintained repositories would
make divergence a certainty, and this project has already produced two forks of exactly that
kind: the operating point between motor_model.py and sizing.py (now guarded by
_check_operating_point), and the paper figures against the analysis (now regenerated by
paper/make_figures.py). This is the same answer applied a third time.

The companions are OUTPUT. Nothing in them is authored. Every generated file carries a header
saying so and naming the flagship commit it came from. If a companion is ever hand-edited, the
correct response is to delete and regenerate it -- not to reconcile the two copies.

USAGE
    python3 tools/export_companion.py --out ../companions          # both
    python3 tools/export_companion.py --out ../companions --only paper

Then, in each generated directory:
    git init && git add -A && git commit && git remote add origin <url> && git push
or use tools/bootstrap_repos.sh, which does that for all of them.
"""
import argparse
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The shared cross-link block. Byte-identical in all four repositories -- the flagship's copy
# in PROGRAMME.md is the source, and this is checked by tools/check_links.py.
HEADER_ROWS = [
    ("VOLLEY", "Flagship: the authoritative engineering record, and the portfolio", ""),
    ("VOLLEY-paper", "IEEE companion: manuscript and reproducibility package *(generated)*", "paper"),
    ("VOLLEY-thesis", "Thesis companion: university submission *(generated)*", "thesis"),
    ("VOLLEY-lab", "Phase II: research, redesign, deliberately unstable", "lab"),
]
OWNER = "aaaaaaaaaaaavm"

# The generated directory name has to match the repository it is pushed to. Override it if the
# repositories have not been renamed yet:
#
#     REPO_PREFIX=EMOCD python3 tools/export_companion.py --out ../companions
#
# Getting this wrong does not fail loudly. `gh repo create` in bootstrap_repos.sh would simply
# create a second, empty repository under the other name and push to that, leaving the real one
# untouched and the mistake invisible until someone opens the wrong URL.
REPO_PREFIX = os.environ.get("REPO_PREFIX", "VOLLEY")
# The flagship repository these are generated from. Follows REPO_PREFIX so the
# provenance banner cannot point at a repository name that no longer exists.
FLAGSHIP = REPO_PREFIX


def header_table(here):
    """`here` is '', 'paper', 'thesis' or 'lab'."""
    out = ["<!-- PROGRAMME-HEADER-START -->",
           "| Repository | Role | You are here |", "|---|---|---|"]
    for name, role, key in HEADER_ROWS:
        link = f"[{name}](https://github.com/{OWNER}/{name})"
        cell = f"**{link}**" if key == here else link
        out.append(f"| {cell} | {role} | {'←' if key == here else ''} |")
    out.append("<!-- PROGRAMME-HEADER-END -->")
    return "\n".join(out)


def banner(commit, kind):
    return f"""> ## Generated repository, do not edit here
>
> Every file in this repository is generated from the **VOLLEY flagship** by
> `tools/export_companion.py`. Nothing here is authored, and any edit made here will be
> destroyed the next time it is regenerated.
>
> **Source:** [{OWNER}/{FLAGSHIP}](https://github.com/{OWNER}/{FLAGSHIP}) at commit `{commit}`
> **Found a mistake?** Fix it in the flagship. This repository will pick it up.
>
> The flagship is the authoritative engineering record. Where this repository and the
> flagship disagree, the flagship is right and this copy is stale.

{header_table(kind)}
"""


# path in flagship -> path in companion. Directories copied recursively.
PAPER_MANIFEST = [
    ("paper/paper.tex", "paper/paper.tex"),
    ("paper/IEEEtran.cls", "paper/IEEEtran.cls"),
    ("paper/VOLLEY_IEEE_Conference.pdf", "paper/VOLLEY_IEEE_Conference.pdf"),
    ("paper/figures", "paper/figures"),
    ("paper/make_figures.py", "paper/make_figures.py"),
    ("analysis", "analysis"),
    ("requirements.txt", "requirements.txt"),
    ("validation", "validation"),
    ("docs/PROVENANCE.md", "PROVENANCE.md"),
    ("docs/PRIOR_ART.md", "PRIOR_ART.md"),
    ("docs/LITERATURE.md", "LITERATURE.md"),
    ("docs/BASELINE.md", "BASELINE.md"),
    ("LICENSE", "LICENSE"),
    ("CITATION.cff", "CITATION.cff"),
]

THESIS_MANIFEST = [
    ("paper/paper.tex", "source/paper.tex"),
    ("paper/VOLLEY_IEEE_Conference.pdf", "source/VOLLEY_IEEE_Conference.pdf"),
    ("paper/figures", "source/figures"),
    ("analysis", "analysis"),
    ("validation", "validation"),
    ("cad", "cad"),
    ("docs/BASELINE.md", "appendix/BASELINE.md"),
    ("OPEN_PROBLEMS.md", "appendix/OPEN_PROBLEMS.md"),
    ("docs/VALIDATION_REPORT.md", "appendix/VALIDATION_REPORT.md"),
    ("docs/PROVENANCE.md", "appendix/PROVENANCE.md"),
    ("CHANGELOG.md", "appendix/CHANGELOG.md"),
    ("docs/HISTORY.md", "appendix/HISTORY.md"),
    ("docs/DECISION_LOG.md", "appendix/DECISION_LOG.md"),
    ("docs/adr", "appendix/adr"),
    ("docs/PRIOR_ART.md", "appendix/PRIOR_ART.md"),
    ("docs/LITERATURE.md", "appendix/LITERATURE.md"),
    ("docs/RELATED_WORK.md", "appendix/RELATED_WORK.md"),
    ("LICENSE", "LICENSE"),
]

PAPER_README = """# VOLLEY: IEEE companion

Everything needed to reproduce the conference paper. Manuscript source, figures, the analysis
scripts behind every number in it, the validation run sheets, and the literature record.

**[Read the paper](paper/VOLLEY_IEEE_Conference.pdf)** (11 pages)

## Reproduce it in one command

```bash
pip install -r requirements.txt
cd analysis && python3 verify_field.py && python3 mass_properties.py \\
  && python3 motor_model.py && python3 sizing.py && python3 astro.py && python3 cost.py
```

Roughly two minutes. Results land in `analysis/results/*.json`.

This has been checked from a clean clone rather than assumed: run that way, `motor_results.json`
returns `shot.v_exit = 16.537`, which is the figure the paper's abstract quotes.

## What reproduces, and how well

| Quantity | Value | Cross-checked against |
|---|---|---|
| Thrust constant | 11.22 N per kA/m | A meshed magnetostatic FEM, agreeing to 0.07 % |
| Airgap field | 0.694 T midgap peak | magpylib, agreeing to three digits |
| Orbital decay | x1.62 lifetime | Cowell RK4, agreeing to 99.4 % |
| Exit velocity | 16.537 m/s at 10.7 g | Single-sourced |
| Dispersion | 0.027 m/s, 3 sigma | Single-sourced, and resting on assumed sensor noise |

The last two have no independent check. `PROVENANCE.md` says which of these carry weight.

## Figures

`python3 paper/make_figures.py` regenerates all of them. It imports the analysis rather than
reimplementing it, so a figure cannot quietly disagree with the number it plots.

## Before citing

**Read [`PROVENANCE.md`](PROVENANCE.md).** This is a design study at TRL 2-3. Nothing has been
built, fired or measured, and the paper says so.

[`PRIOR_ART.md`](PRIOR_ART.md) records the published work nearest to this one, including two
claims the paper had to retract after reading it. [`LITERATURE.md`](LITERATURE.md) maps the wider
field.

## What is deliberately absent

The engineering record. Decision log, defect ledger, CAD generations, roadmap and change history
live in the flagship. This package exists so the paper can be checked, not so it can stand in for
the repository it came from.
"""

THESIS_README = """# VOLLEY: thesis companion

Final-year thesis submission material, generated from the VOLLEY flagship.

**[Read the manuscript](source/VOLLEY_IEEE_Conference.pdf)**

## Layout

| | |
|---|---|
| `source/` | Manuscript and figures |
| `analysis/` | Six scripts producing every number in the work |
| `validation/` | Nine analyses, each with its acceptance band declared before the run |
| `cad/` | Three CAD generations, with the defect audit for each |
| `appendix/` | Baseline, defect ledger, validation report, provenance, prior art, literature, decision records |

## For an examiner, in reading order

1. `appendix/PROVENANCE.md`, which says what stands behind each claim and what does not.
2. `appendix/BASELINE.md`, the twenty frozen values, and the rule for changing any of them.
3. `appendix/adr/`, eighteen decision records. Each states the alternatives considered and the
   consequences accepted. ADR-003 carries its own amendment showing an argument it got wrong.
4. `appendix/OPEN_PROBLEMS.md`, every known defect, including the ones that damage the work's own
   claims.
5. `appendix/PRIOR_ART.md`, the nearest published work, and the two claims retracted after reading
   it.

The decision records are the part most worth reading. They are where the reasoning lives, and
several of them record the alternative that was rejected and why.

## University material goes in `university/`

That directory is the one place in this repository where hand-written content survives.
Submission forms, formatting mandates and viva material are university-specific and do not belong
upstream. **Everything outside `university/` is regenerated and will be overwritten.**

## Before citing

Every number here is a model output. Nothing has been built or measured. The defect ledger is
published deliberately rather than tidied away, and it is the honest measure of how far the work
has actually got.
"""


def copy(src, dst):
    s, d = os.path.join(ROOT, src), os.path.join(dst)
    os.makedirs(os.path.dirname(d) or d, exist_ok=True)
    if os.path.isdir(s):
        shutil.copytree(s, d, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', 'output'))
    elif os.path.exists(s):
        shutil.copy2(s, d)
    else:
        print(f"    MISSING (skipped): {src}")
        return 0
    return 1


def build(kind, manifest, readme, out_root, commit):
    dest = os.path.join(out_root, f"{REPO_PREFIX}-{kind}")
    if os.path.exists(dest):
        shutil.rmtree(dest)          # regenerate wholesale; never merge into a stale tree
    os.makedirs(dest)
    n = sum(copy(src, os.path.join(dest, rel)) for src, rel in manifest)
    with open(os.path.join(dest, "README.md"), "w") as f:
        f.write(banner(commit, kind) + "\n---\n\n" + readme)
    with open(os.path.join(dest, ".gitignore"), "w") as f:
        f.write("__pycache__/\n*.pyc\n*.aux\n*.log\n*.out\npaper.pdf\n")
    if kind == "thesis":
        os.makedirs(os.path.join(dest, "university"), exist_ok=True)
        with open(os.path.join(dest, "university", "README.md"), "w") as f:
            f.write("# University-specific material\n\n"
                    "**This directory is never touched by `export_companion.py`.** Submission "
                    "forms, templates, formatting mandates and viva material go here.\n\n"
                    "Everything outside this directory is generated and will be overwritten "
                    "on the next export.\n")
    print(f"  VOLLEY-{kind}: {n} paths -> {dest}")
    return dest


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="directory to write the companions into")
    ap.add_argument("--only", choices=["paper", "thesis"], help="build just one")
    args = ap.parse_args()

    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                           capture_output=True, text=True).stdout.strip()
    if dirty:
        print("WARNING: flagship working tree is dirty. The companions will record a commit "
              "that does not match what was copied. Commit first.\n", file=sys.stderr)
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True).stdout.strip()

    out_root = os.path.abspath(args.out)
    os.makedirs(out_root, exist_ok=True)
    print(f"generating companions from flagship {commit} into {out_root}")
    if args.only in (None, "paper"):
        build("paper", PAPER_MANIFEST, PAPER_README, out_root, commit)
    if args.only in (None, "thesis"):
        build("thesis", THESIS_MANIFEST, THESIS_README, out_root, commit)
    print("done. These are output -- do not edit them; edit the flagship and re-run.")


if __name__ == "__main__":
    main()
